config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  root 'pages#welcome'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :courses
  get 'my_courses', to: 'courses#my_courses'
  get 'enrollments', to: 'courses#enrollments'
  get 'enrolled', to: 'courses#enrolled'
  post 'enroll', to: 'grades#enroll'
  get 'edit_grade', to: 'grades#edit_grade'
  post 'update_grade', to: 'grades#update_grade'

  namespace :admin do
    resources :users
  end
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :course
  belongs_to :user
  # validates :grade, numericality: true, inclusion: {in: 0..5, message: 'Value should be between 0 and 5'}
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:edit_grade]

  def enroll
    course_to_add = Course.find(params[:course_id])
    user_to_enroll = User.find(params[:user_id])

    if !user_to_enroll.courses.include?(course_to_add)
      Grade.create(course_id: course_to_add.id, user_id: user_to_enroll.id)
      flash[:success] = "#{user_to_enroll.first_name + ' ' + user_to_enroll.last_name } has been successfully enrolled in #{course_to_add.name}"
      redirect_to enrollments_path
    else
      flash[:alert] = "#{user_to_enroll.email} is already enrolled in #{course_to_add.name}"
      redirect_to courses_path
    end
  end

  def edit_grade
    respond_to do |format|
      format.html
      format.js { render partial: 'grades/edit_grade' }
    end
  end

  def update_grade
    @grade = Grade.find(params[:grade])
    respond_to do |format|
      if @grade.update(grade: params[:grade_avg])
        format.js { render partial: 'grades/current_grade' }
      else
        format.html { redirect_to enrolled_path(id: @grade.course), alert: @grade.errors[:grade][0] }
      end
    end
  end

  private

  def set_grade
    @grade = Grade.where(course_id: params[:course_id], user_id: params[:user_id]).last
  end
end

app/views/grades/_current_grade.html.erb
  <%= student.grade_for(course) %>

app/views/grades/_current_grade.js.erb
document.querySelector('#grade').innerHTML = "<%= escape_javascript(render 'grades/current_grade.html', student: @grade.user, course: @grade.course)%>";

app/views/grades/_edit_grade.html.erb
<%= form_with(url: update_grade_path(grade: @grade), remote: true) do |f| %>
  <%= f.text_field :grade_avg, required: true, disabled: !current_user.teacher?, class:"materialize-textarea", maxlength:"3" %>
<% end %>

app/views/grades/_edit_grade.js.erb
document.querySelector('#grade').innerHTML = "<%= escape_javascript(render 'grades/edit_grade.html')%>";