config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  root 'pages#welcome'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :courses
  get 'my_courses', to: 'courses#my_courses'
  get 'enrollments', to: 'courses#enrollments'
  get 'enrolled', to: 'courses#enrolled'
  post 'enroll', to: 'grades#enroll'
  get 'edit_grade', to: 'grades#edit_grade'
  post 'update_grade', to: 'grades#update_grade'

  namespace :admin do
    resources :users
  end
end

app/views/shared/_footer.html.erb
<footer class="page-footer orange darken-1">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">SI - University</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2020 Copyright - Developed by Fernando Bello
    <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
        toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
  </script>
<% end %>

app/views/shared/_navigation.html.erb
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to 'All Courses', courses_path %></li>
  <% if user_signed_in? %>
    <% if current_user.student? %>
      <li><%= link_to 'Enrollments', enrollments_path %></li>
    <% elsif current_user.teacher? %>
      <li><%= link_to 'My Courses', my_courses_path %></li>
      <% if can? :create, Course %>
        <li class="divider" tabindex="-1"></li>
        <li><%= link_to 'Create Course', new_course_path %></li>
      <% end %>
    <% end %>
  <% end %>
</ul>

<ul id="dropdown2" class="dropdown-content">
  <li><%= link_to 'All Users', admin_users_path %></li>
</ul>

<nav class='orange darken-1'>
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to root_path, class: 'brand-logo right' do %>SI - University<% end %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <% if user_signed_in? %>
        <ul class="left hide-on-med-and-down">
          <% if user_signed_in? %>
            <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Courses<i class="material-icons right">arrow_drop_down</i></a></li>
            <% if current_user.admin? %>
              <li><%= link_to 'All Users', admin_users_path %></li>
            <% end %>
            <li><%= link_to "<i class='material-icons right'>person</i>#{current_user.first_name + ' ' + current_user.last_name}".html_safe, edit_user_registration_path %></li>
            <li><%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %></li>
          <% end %>
        </ul>
        <% else %>
          <ul class="left hide-on-med-and-down">
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Log in', new_user_session_path %></li>
          </ul>
      <% end %>

      <ul class="sidenav" id="mobile-demo">
        <% if user_signed_in? %>
          <li><div class="user-view">
            <div class="background">
            </div>
            <a href="#user"><img class="circle" src="assets/avatar.png"></a>
            <a href="#name"><span class="white-text name"><%= current_user.username %></span></a>
            <a href="#email"><span class="white-text email"><%= current_user.email %></span></a>
          </div></li>
          <li><%= link_to 'All Courses', courses_path %></li>
          <% if current_user.student? %>
            <li><%= link_to 'Enrollments', enrollments_path %></li>
          <% elsif current_user.teacher? %>
            <li><%= link_to 'My Courses', my_courses_path %></li>
            <% if can? :create, Course %>
              <li><%= link_to 'Create Course', new_course_path %></li>
            <% end %>
          <% end %>
          <% if current_user.admin? %>
            <li><%= link_to 'All Users', admin_users_path %></li>
          <% end %>
          <li><div class="divider"></div></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %></li>
        <% else %>
          <li><%= link_to '<i class="material-icons">person_add</i> Sign up '.html_safe, new_user_registration_path %></li>
          <li><%= link_to '<i class="material-icons">account_box</i> Log in '.html_safe, new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>