config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  root 'pages#welcome'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :courses
  get 'my_courses', to: 'courses#my_courses'
  get 'enrollments', to: 'courses#enrollments'
  get 'enrolled', to: 'courses#enrolled'
  post 'enroll', to: 'grades#enroll'
  get 'edit_grade', to: 'grades#edit_grade'
  post 'update_grade', to: 'grades#update_grade'

  namespace :admin do
    resources :users
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :enrolled]
  before_action :set_teachers, only: [:new, :edit]
  load_and_authorize_resource

  def show
  end

  def index
    @courses = Course.all.order(created_at: :desc)
  end

  def my_courses
    @courses = Course.where(teacher_id: current_user.id).order(created_at: :desc)
  end

  def enrollments
    @enrollments = current_user.courses.order(short_name: :asc)
  end

  def enrolled
    @enrolled = @course.users
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      flash[:success] = 'Course was successfully created.'
      redirect_to courses_path
    else
      flash[:alert] = 'An error occurred while course creation.'
      redirect_to new_course_path
    end
  end

  def update
    if @course.update(course_params)
      flash[:success] = 'Course was successfully updated.'
      redirect_to course_path
    else
      flash[:alert] = 'An error occurred while the update was performed.'
      redirect_to edit_course_path
    end
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def set_teachers
    @teachers = User.teachers
  end

  def course_params
    params.require(:course).permit(:short_name, :name, :description, :teacher_id)
  end
end

app/views/courses/_course.html.erb
<div class="col s12 m6">
  <div class="course-card card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= course.name %></span>
      <%= link_to '<i class="material-icons">add</i>'.html_safe,
        course_path(course),
        class: "btn-floating halfway-fab waves-effect waves-light orange darken-1" %>
      <p><%= truncate(course.description, length: 120) %></p>
    </div>
    <div class="card-action">
      <% if (can? :enroll, Grade) && current_user.student? && !current_user.courses.include?(course) %>
        <%= link_to 'Enroll', enroll_path(course_id: course.id, user_id: current_user.id), method: :post %>
      <% end %>
    </div>
  </div>
</div>

app/views/courses/_form.html.erb
<div class="container">
  <div class="row center sign-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <div class="row">
          <%= form_with(model: course, local: true, html: { class: "col s12" }) do |f| %>

            <div class="input-field col s12">
              <%= f.label :short_name %><br />
              <%= f.text_field :short_name, autofocus: true, required: true, disabled: !current_user.admin?, class:"materialize-textarea", maxlength:"4" %>
            </div>

            <div class="input-field col s12">
              <%= f.label :name %><br />
              <%= f.text_field :name, required: true, disabled: !current_user.admin?, class:"materialize-textarea", maxlength:"50" %>
            </div>

            <div class="input-field col s12">
              <%= f.label :description %><br />
              <%= f.text_area :description, id:"textarea2", class: "materialize-textarea", maxlength:"300" %>
            </div>

            <div class="input-field col s12">
              <div class=<%= 'disabled' if !current_user.admin? %>>
                <%= f.select :teacher_id, @teachers.collect { |t| [ t.email, t.id ] }, include_blank: true, prompt: 'Choose teacher' %>
                <label>Teacher</label>
              </div>
            </div>

            <button class="btn cyan darken-1 waves-effect waves-light" type="submit" name="action">Submit</button>
            <br/>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/edit.html.erb
<h1 class='center'>Editing Course [<%= @course.name %>]</h1>

<%= render 'form', course: @course %>

app/views/courses/enrolled.html.erb
<h1>Enrolled students in <%= @course.name %></h1>
<table class='highlight centered'>
  <thead>
    <tr>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Grade</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
  <% @enrolled.each do |student| %>
    <tr>
      <td><%= student.username %></td>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td>
        <div id='grade'>
          <%= student.grade_for(@course) %>
        </div>
      </td>
      <td>
        <% if current_user == @course.teacher %>
          <%= link_to '<i class="material-icons left">grade</i>Edit grade'.html_safe, edit_grade_path(course_id: @course.id, user_id: student.id), remote: true, class:"waves-effect waves-light btn light-blue darken-1"%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/enrollments.html.erb
<h1>Enrollments</h1>
<table class='highlight centered'>
  <thead>
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
  <% @enrollments.each do |course| %>
    <tr>
      <td><%= course.short_name %></td>
      <td><%= course.name %></td>
      <td>
        <%= link_to '<i class="material-icons left">people</i>Enrolled students'.html_safe, enrolled_path(id: course.id), class:"waves-effect waves-light btn light-blue darken-1"%>
        <%= link_to '<i class="material-icons right">more_horiz</i>Detail'.html_safe, course_path(course), class:"waves-effect waves-light btn yellow darken-3"%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/index.html.erb
<h1 class='center'>Courses</h1>
<div class="row">
  <% @courses.each do |course| %>
    <%= render 'course', course: course %>
  <% end %>
</div>

app/views/courses/my_courses.html.erb
<h1>My Courses</h1>
<table class='highlight centered'>
  <thead>
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
    <tr>
      <td><%= course.short_name %></td>
      <td><%= course.name %></td>
      <td>
        <% if can? :enrolled, Course %>
          <%= link_to '<i class="material-icons left">people</i>Enrolled students'.html_safe, enrolled_path(id: course.id), class:"waves-effect waves-light btn light-blue darken-1"%>
        <% end %>
        <%= link_to '<i class="material-icons right">more_horiz</i>Detail'.html_safe, course_path(course), class:"waves-effect waves-light btn yellow darken-3"%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/courses/new.html.erb
<h1 class='center'>Create Course</h1>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<div class="row">
  <div class="col s12">
    <h1 class='center'>
      <%= @course.name %>
    </h1>
  </div>
  <div class="col s6">
    <div class="card-panel blue-grey darken-1">
      <span class="white-text">
        <p><b>Code: </b><%= @course.short_name %></p>
        <p><b>Course description: </b> <%= @course.description%></p>
        <p><b>Enrolled students: </b><%= @course.users.count %></p>
      </span>
    </div>
  </div>
  <div class="col s6 right-align">
    <% if user_signed_in? %>
      <% if current_user.teacher? %>
        <% if can? :enrolled, @course %>
          <%= link_to '<i class="material-icons left">people</i>Enrolled students'.html_safe, enrolled_path(id: @course.id), class:"waves-effect waves-light btn light-blue darken-1"%>
        <% end %>
        <% if can? :edit, @course %>
          <%= link_to '<i class="material-icons left">mode_edit</i>Edit'.html_safe, edit_course_path(@course), class:"waves-effect waves-light btn yellow darken-3"%>
        <% end %>
      <% end %>
      <% if current_user.admin? %>
        <a class="waves-effect waves-light btn red darken-3"><i class="material-icons left">delete_forever</i>Delete</a>
      <% end %>
    <% end %>
  </div>
  <div class="col s12">
    <h1 class='center'>
      Announcements
    </h1>
  </div>
</div>