config/routes.rb
Rails.application.routes.draw do
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # resources :users, only: [:show, :destroy], :constraints => { :id => /[0-9|]+/ }
  root 'pages#welcome'
  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  resources :courses
  get 'my_courses', to: 'courses#my_courses'
  get 'enrollments', to: 'courses#enrollments'
  get 'enrolled', to: 'courses#enrolled'
  post 'enroll', to: 'grades#enroll'
  get 'edit_grade', to: 'grades#edit_grade'
  post 'update_grade', to: 'grades#update_grade'

  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  before_save :downcase_email, :downcase_role, :set_username
  validates :first_name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :last_name, presence: true, length: { minimum: 5, maximum: 100 }
  VALID_EMAIL_REGEX = /\A[^@\s]+@([^@\s]+\.)+[^@\W]+\z/
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                      length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, if: :new_user?
  validates :role, presence: true, inclusion: { in: %w[Student Teacher] }, if: :new_user?

  has_many :grades
  has_many :courses, through: :grades, dependent: :destroy

  has_many :teaching_courses, class_name: "Course", foreign_key: :teacher_id

  scope(:students, -> { where(role: 'student') })
  scope(:teachers, -> { where(role: 'teacher') })

  def student?
    role == 'student'
  end

  def teacher?
    role == 'teacher'
  end

  def admin?
    is_admin?
  end

  def grade_for(course)
    Grade.where(course_id: course.id, user_id: id).last.grade || '--'
  end

  private

  def new_user?
    new_record?
  end

  def set_username
    self.username = (first_name.slice(0) + last_name.split[0]).downcase
  end

  def downcase_email
    self.email = email.downcase
  end

  def downcase_role
    self.role = role.downcase
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseAdminController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all.order(created_at: :desc)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated.'
      redirect_to admin_users_path
    else
      flash[:alert] = 'An error occurred while the update was performed.'
      redirect_to edit_user_path
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :num, :major, :email, :role)
  end
end

app/views/admin/users/_form.html.erb
<div class="container">
  <div class="row center sign-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <div class="row">
          <%= form_with(model: [:admin, user], local: true, html: { class: "col s12" }) do |f| %>

            <div class="input-field col s6">
              <%= f.label :first_name %><br />
              <%= f.text_field :first_name, required: true, disabled: !current_user.admin?, class:"materialize-textarea", maxlength:"50" %>
            </div>

            <div class="input-field col s6">
              <%= f.label :last_name %><br />
              <%= f.text_field :last_name, required: true, disabled: !current_user.admin?, class:"materialize-textarea", maxlength:"50" %>
            </div>

            <div class="input-field col s6">
              <%= f.label :username %><br />
              <%= f.text_field :username, required: true, disabled: !current_user.admin?, class:"materialize-textarea", maxlength:"50" %>
            </div>

            <div class="input-field col s6">
              <div class=<%= 'disabled' if !current_user.admin? %>>
                <br />
                <%= f.select :role, options_for_select([:Student, :Teacher]), :include_blank => false, :prompt => 'Choose role' %>
              </div>
            </div>

            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
            </div>

            <button class="btn cyan darken-1 waves-effect waves-light" type="submit" name="action">Submit</button>
            <br/>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h1 class='center'>Editing User [<%= @user.first_name + ' ' + @user.last_name %>]</h1>

<%= render 'form', user: @user %>

app/views/admin/users/index.html.erb
<h1>Users</h1>
<table class='highlight centered responsive-table'>
  <thead>
    <tr>
        <th>Email</th>
        <th>Role</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.role.capitalize %></td>
      <td>
        <%= link_to '<i class="material-icons left">mode_edit</i>Edit'.html_safe, edit_admin_user_path(user), class:"waves-effect waves-light btn yellow darken-3"%>
        <%= link_to '<i class="material-icons left">delete_forever</i>Delete account'.html_safe, admin_user_path(user), class:"waves-effect waves-light btn red darken-3", data: { confirm: "Are you sure?" }, method: :delete%>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/users/show.html.erb
<h1>Show <%= @user.email %></h1>